# Generated by Django 2.2.5 on 2019-09-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'managed': False, 'ordering': ['name']},
        ),
    ]
