# Generated by Django 2.2.5 on 2019-09-15 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0002_auto_20190915_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'managed': False, 'ordering': ['overall']},
        ),
    ]
