# Generated by Django 2.2.5 on 2019-09-15 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0003_auto_20190915_0922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'managed': False, 'ordering': ['-overall']},
        ),
    ]
